# Generated by Django 4.2.3 on 2024-07-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wemby_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
